[project]
name = "avilla-test"
version = "0.1.0"
description = ""
authors = [
    {name = "Redlnn", email = "w731347477@gmail.com"},
]
dependencies = [
    "aiohttp[speedups]>=3.8.5",
    "aiosqlite>=0.19.0",
    "asyncmy>=0.2.8",
    "avilla-core>=1.0.0a6",
    "avilla-console>=0.2.0",
    "avilla-standard-qq>=1.0.0a6",
    "avilla-qqguild-tencent>=1.0.0a6",
    "creart>=0.3.0",
    "dnspython>=2.4.1",
    "graia-amnesia>=0.8.2",
    "graia-broadcast>=0.23.2",
    "graia-saya>=0.0.18",
    "kayaku>=0.5.2",
    "launart>=0.7.0",
    "orjson>=3.9.3",
    "psutil>=5.9.5",
    "sqlalchemy[asyncio]>=2.0.19",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "AGPL-3.0-only"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.7.0",
    "isort>=5.12.0",
    "ruff>=0.0.282",
]

[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true
safe = true

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120
target-version = "py311"
select = [
    # https://beta.ruff.rs/docs/rules
    "E",  # pycodestyle
    "F",  # pyflakes
    "UP", # pyupgrade
    "I",  # isort
    # "D",  # pydocstyle
    "ASYNC", # flake8-async
]
exclude = [
    ".git",
    ".venv",
    "__pypackages__",
    "dist",
]
ignore = ["F401"]

[tool.ruff.pydocstyle]
convention = "google"
